name: CI

on:
  pull_request:
    branches:
    - master

jobs:
  test:
    name: awesome_bot verification
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v1
      - name: Run awesome_bot
        uses: docker://dkhamsing/awesome_bot:latest
        with:
          args: README.md
